spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    properties:
      javax:
        persistence:
          validation:
            mode: none
  h2:
    console:
      enabled: true
